export const ASSESSMENT_TYPES = Object.freeze({
  MCQ: "MCQ",
  CODING: "CODING",
  VIDEO_INTERVIEW: "VIDEO_INTERVIEW",
  HYBRID: "HYBRID",
  ESSAY: "ESSAY",
  EXAMINATION: "EXAMINATION",
  QUIZ: "QUIZ",
  FILE_UPLOAD: "FILE_UPLOAD",
  ORAL: "ORAL",
  PRACTICAL: "PRACTICAL",
  SKILLS: "SKILLS",
  CUSTOM: "CUSTOM",
});

export const ASSESSMENT_TYPE_LIST = Object.values(ASSESSMENT_TYPES);
