export const ASSESSMENT_STATUSES = Object.freeze({
  DRAFT: "DRAFT",
  READY_FOR_REVIEW: "READY_FOR_REVIEW",
  APPROVED: "APPROVED",
  PUBLISHED: "PUBLISHED",
  ACTIVE: "ACTIVE",
  CLOSED: "CLOSED",
  ARCHIVED: "ARCHIVED",
});

export const ASSESSMENT_STATUS_LIST = Object.values(ASSESSMENT_STATUSES);

export const EDITABLE_ASSESSMENT_STATUSES = [
  ASSESSMENT_STATUSES.DRAFT,
  ASSESSMENT_STATUSES.READY_FOR_REVIEW,
  ASSESSMENT_STATUSES.APPROVED,
];
