export const ATTEMPT_STATUSES = Object.freeze({
  NOT_STARTED: "NOT_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  PAUSED: "PAUSED",
  SUBMITTED: "SUBMITTED",
  AUTO_SUBMITTED: "AUTO_SUBMITTED",
  EVALUATING: "EVALUATING",
  COMPLETED: "COMPLETED",
  EXPIRED: "EXPIRED",
  ABANDONED: "ABANDONED",
  TERMINATED: "TERMINATED",
  TERMINATED_DUE_TO_VIOLATION: "TERMINATED_DUE_TO_VIOLATION",
});

export const ATTEMPT_STATUS_LIST = Object.values(ATTEMPT_STATUSES);
