export const PROCTORING_STATUSES = Object.freeze({
  NOT_STARTED: "NOT_STARTED",
  INITIALIZING: "INITIALIZING",
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  ENDED: "ENDED",
  TERMINATED: "TERMINATED",
  FAILED: "FAILED",
});

export const PROCTORING_STATUS_LIST = Object.values(PROCTORING_STATUSES);

export const INTEGRITY_STATUSES = Object.freeze({
  CLEAR: "CLEAR",
  LOW_RISK: "LOW_RISK",
  MEDIUM_RISK: "MEDIUM_RISK",
  HIGH_RISK: "HIGH_RISK",
  CRITICAL: "CRITICAL",
  UNDER_REVIEW: "UNDER_REVIEW",
  FLAGGED: "FLAGGED",
  CONFIRMED_VIOLATION: "CONFIRMED_VIOLATION",
  DISQUALIFIED: "DISQUALIFIED",
});

export const INTEGRITY_STATUS_LIST = Object.values(INTEGRITY_STATUSES);

export const PROCTORING_EVENT_TYPES = Object.freeze({
  // Browser & Environment Events
  TAB_SWITCH: "TAB_SWITCH",
  WINDOW_BLUR: "WINDOW_BLUR",
  WINDOW_FOCUS: "WINDOW_FOCUS",
  FULLSCREEN_EXIT: "FULLSCREEN_EXIT",
  FULLSCREEN_EXITED: "FULLSCREEN_EXITED",
  FULLSCREEN_ENTERED: "FULLSCREEN_ENTERED",
  COPY_ATTEMPT: "COPY_ATTEMPT",
  PASTE_ATTEMPT: "PASTE_ATTEMPT",
  RIGHT_CLICK: "RIGHT_CLICK",
  DEVTOOLS_DETECTED: "DEVTOOLS_DETECTED",

  // Hardware & Media Stream Events
  CAMERA_DISABLED: "CAMERA_DISABLED",
  CAMERA_ENABLED: "CAMERA_ENABLED",
  MICROPHONE_DISABLED: "MICROPHONE_DISABLED",
  MICROPHONE_ENABLED: "MICROPHONE_ENABLED",
  SCREEN_SHARE_STOPPED: "SCREEN_SHARE_STOPPED",
  SCREEN_SHARE_STARTED: "SCREEN_SHARE_STARTED",

  // Vision & AI Anomaly Detection Events
  FACE_NOT_DETECTED: "FACE_NOT_DETECTED",
  NO_FACE_DETECTED: "NO_FACE_DETECTED",
  MULTIPLE_FACES: "MULTIPLE_FACES",
  MULTIPLE_FACES_DETECTED: "MULTIPLE_FACES_DETECTED",
  FACE_CHANGED: "FACE_CHANGED",
  SUSPICIOUS_AUDIO: "SUSPICIOUS_AUDIO",
  SUSPICIOUS_OBJECT: "SUSPICIOUS_OBJECT",

  // Connectivity & Session Lifecycle Events
  NETWORK_DISCONNECTED: "NETWORK_DISCONNECTED",
  NETWORK_RECONNECTED: "NETWORK_RECONNECTED",
  SESSION_INTERRUPTED: "SESSION_INTERRUPTED",
  PROCTORING_STARTED: "PROCTORING_STARTED",
  PROCTORING_ENDED: "PROCTORING_ENDED",
  PROCTOR_WARNING: "PROCTOR_WARNING",
});

export const PROCTORING_EVENT_TYPE_LIST = Object.values(PROCTORING_EVENT_TYPES);

export const EVENT_SEVERITIES = Object.freeze({
  INFO: "INFO",
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});

export const EVENT_SEVERITY_LIST = Object.values(EVENT_SEVERITIES);

export const RISK_LEVELS = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});

export const RISK_LEVEL_LIST = Object.values(RISK_LEVELS);
