export const RESULT_STATUSES = Object.freeze({
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  PUBLISHED: "PUBLISHED",
  WITHHELD: "WITHHELD",
  CANCELLED: "CANCELLED",
  PASS: "PASS",
  FAIL: "FAIL",
  NEEDS_MANUAL_REVIEW: "NEEDS_MANUAL_REVIEW",
  FLAGGED: "FLAGGED",
});

export const RESULT_STATUS_LIST = Object.values(RESULT_STATUSES);
