export const SUBSCRIPTION_PLANS = Object.freeze({
  FREE_TRIAL: "FREE_TRIAL",
  STARTER: "STARTER",
  PROFESSIONAL: "PROFESSIONAL",
  ENTERPRISE: "ENTERPRISE",
  CUSTOM: "CUSTOM",
});

export const SUBSCRIPTION_PLAN_LIST = Object.values(SUBSCRIPTION_PLANS);
