export const SYSTEM_CONSTANTS = Object.freeze({
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_PAGE_LIMIT: 100,
  BCRYPT_SALT_ROUNDS: 10,
  ACCESS_TOKEN_EXPIRY: "15m",
  REFRESH_TOKEN_EXPIRY: "7d",
  VERIFICATION_CODE_EXPIRY_MINUTES: 15,
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
});
