export const USER_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INVITED: "INVITED",
  SUSPENDED: "SUSPENDED",
  DEACTIVATED: "DEACTIVATED",
});

export const USER_STATUS_LIST = Object.values(USER_STATUSES);
