import Permission from "../../modules/permissions/permission.model.js";
import Role from "../../modules/roles/role.model.js";
import { PERMISSIONS, PERMISSION_LIST } from "../../constants/permissions.js";
import {
  PLATFORM_ROLES,
  ORGANIZATION_ROLES,
  ROLE_SCOPES,
} from "../../constants/roles.js";
import { logger } from "../../config/logger.js";

/**
 * Maps each system role to its baseline permission keys
 */
const ROLE_PERMISSION_MATRIX = {
  [PLATFORM_ROLES.PLATFORM_OWNER]: PERMISSION_LIST, // Every single platform and organization permission

  [PLATFORM_ROLES.PLATFORM_ADMIN]: [
    PERMISSIONS.PLATFORM_VIEW,
    PERMISSIONS.PLATFORM_ANALYTICS_VIEW,
    PERMISSIONS.PLATFORM_MONITORING_VIEW,
    PERMISSIONS.ORGANIZATIONS_VIEW,
    PERMISSIONS.ORGANIZATIONS_UPDATE,
    PERMISSIONS.ORGANIZATIONS_SUSPEND,
    PERMISSIONS.PLATFORM_USERS_VIEW,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.PERMISSIONS_VIEW,
    PERMISSIONS.SUBSCRIPTIONS_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.AUDIT_LOGS_VIEW,
  ],

  [ORGANIZATION_ROLES.ORGANIZATION_OWNER]: [
    // Organization management
    PERMISSIONS.ORG_PROFILE_VIEW,
    PERMISSIONS.ORG_PROFILE_UPDATE,
    PERMISSIONS.ORG_USERS_CREATE,
    PERMISSIONS.ORG_USERS_VIEW,
    PERMISSIONS.ORG_USERS_UPDATE,
    PERMISSIONS.ORG_USERS_SUSPEND,
    PERMISSIONS.ORG_USERS_REMOVE,
    PERMISSIONS.DEPARTMENTS_CREATE,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.DEPARTMENTS_UPDATE,
    PERMISSIONS.DEPARTMENTS_DELETE,
    PERMISSIONS.PROGRAMS_CREATE,
    PERMISSIONS.PROGRAMS_VIEW,
    PERMISSIONS.PROGRAMS_UPDATE,
    PERMISSIONS.PROGRAMS_DELETE,
    PERMISSIONS.SUBJECTS_CREATE,
    PERMISSIONS.SUBJECTS_VIEW,
    PERMISSIONS.SUBJECTS_UPDATE,
    PERMISSIONS.SUBJECTS_DELETE,
    // Question Bank
    PERMISSIONS.QUESTION_BANKS_CREATE,
    PERMISSIONS.QUESTION_BANKS_VIEW,
    PERMISSIONS.QUESTION_BANKS_UPDATE,
    PERMISSIONS.QUESTION_BANKS_DELETE,
    PERMISSIONS.QUESTIONS_CREATE,
    PERMISSIONS.QUESTIONS_VIEW,
    PERMISSIONS.QUESTIONS_UPDATE,
    PERMISSIONS.QUESTIONS_DELETE,
    PERMISSIONS.QUESTIONS_PUBLISH,
    PERMISSIONS.QUESTION_CATEGORIES_CREATE,
    PERMISSIONS.QUESTION_CATEGORIES_VIEW,
    PERMISSIONS.QUESTION_CATEGORIES_UPDATE,
    PERMISSIONS.QUESTION_CATEGORIES_DELETE,
    PERMISSIONS.QUESTION_TAGS_CREATE,
    PERMISSIONS.QUESTION_TAGS_VIEW,
    PERMISSIONS.QUESTION_TAGS_UPDATE,
    PERMISSIONS.QUESTION_TAGS_DELETE,
    // Assessments
    PERMISSIONS.ASSESSMENTS_CREATE,
    PERMISSIONS.ASSESSMENTS_VIEW,
    PERMISSIONS.ASSESSMENTS_UPDATE,
    PERMISSIONS.ASSESSMENTS_DELETE,
    PERMISSIONS.ASSESSMENTS_PUBLISH,
    PERMISSIONS.ASSESSMENTS_ARCHIVE,
    PERMISSIONS.ASSESSMENT_SECTIONS_CREATE,
    PERMISSIONS.ASSESSMENT_SECTIONS_VIEW,
    PERMISSIONS.ASSESSMENT_SECTIONS_UPDATE,
    PERMISSIONS.ASSESSMENT_SECTIONS_DELETE,
    PERMISSIONS.ASSESSMENT_QUESTIONS_ADD,
    PERMISSIONS.ASSESSMENT_QUESTIONS_VIEW,
    PERMISSIONS.ASSESSMENT_QUESTIONS_UPDATE,
    PERMISSIONS.ASSESSMENT_QUESTIONS_REMOVE,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_CREATE,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_VIEW,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_UPDATE,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_CANCEL,
    // Attempts & Proctoring
    PERMISSIONS.ATTEMPTS_VIEW,
    PERMISSIONS.PROCTORING_VIEW,
    PERMISSIONS.PROCTORING_MONITOR,
    PERMISSIONS.PROCTORING_REVIEW,
    PERMISSIONS.PROCTORING_FLAG,
    PERMISSIONS.PROCTORING_RESOLVE,
    // Evaluations & Results
    PERMISSIONS.EVALUATIONS_CREATE,
    PERMISSIONS.EVALUATIONS_VIEW,
    PERMISSIONS.EVALUATIONS_UPDATE,
    PERMISSIONS.EVALUATIONS_SUBMIT,
    PERMISSIONS.EVALUATIONS_APPROVE,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_GENERATE,
    PERMISSIONS.RESULTS_PUBLISH,
    PERMISSIONS.RESULTS_EXPORT,
    PERMISSIONS.CERTIFICATES_GENERATE,
    PERMISSIONS.CERTIFICATES_VIEW,
    PERMISSIONS.CERTIFICATES_REVOKE,
    PERMISSIONS.CERTIFICATES_EXPORT,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AUDIT_LOGS_VIEW,
  ],

  [ORGANIZATION_ROLES.ORGANIZATION_ADMIN]: [
    PERMISSIONS.ORG_PROFILE_VIEW,
    PERMISSIONS.ORG_USERS_CREATE,
    PERMISSIONS.ORG_USERS_VIEW,
    PERMISSIONS.ORG_USERS_UPDATE,
    PERMISSIONS.ORG_USERS_SUSPEND,
    PERMISSIONS.DEPARTMENTS_CREATE,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.DEPARTMENTS_UPDATE,
    PERMISSIONS.PROGRAMS_CREATE,
    PERMISSIONS.PROGRAMS_VIEW,
    PERMISSIONS.PROGRAMS_UPDATE,
    PERMISSIONS.SUBJECTS_CREATE,
    PERMISSIONS.SUBJECTS_VIEW,
    PERMISSIONS.SUBJECTS_UPDATE,
    PERMISSIONS.QUESTION_BANKS_CREATE,
    PERMISSIONS.QUESTION_BANKS_VIEW,
    PERMISSIONS.QUESTION_BANKS_UPDATE,
    PERMISSIONS.QUESTIONS_CREATE,
    PERMISSIONS.QUESTIONS_VIEW,
    PERMISSIONS.QUESTIONS_UPDATE,
    PERMISSIONS.QUESTION_CATEGORIES_CREATE,
    PERMISSIONS.QUESTION_CATEGORIES_VIEW,
    PERMISSIONS.QUESTION_CATEGORIES_UPDATE,
    PERMISSIONS.QUESTION_TAGS_CREATE,
    PERMISSIONS.QUESTION_TAGS_VIEW,
    PERMISSIONS.QUESTION_TAGS_UPDATE,
    PERMISSIONS.ASSESSMENTS_CREATE,
    PERMISSIONS.ASSESSMENTS_VIEW,
    PERMISSIONS.ASSESSMENTS_UPDATE,
    PERMISSIONS.ASSESSMENTS_PUBLISH,
    PERMISSIONS.ASSESSMENTS_ARCHIVE,
    PERMISSIONS.ASSESSMENT_SECTIONS_CREATE,
    PERMISSIONS.ASSESSMENT_SECTIONS_VIEW,
    PERMISSIONS.ASSESSMENT_SECTIONS_UPDATE,
    PERMISSIONS.ASSESSMENT_QUESTIONS_ADD,
    PERMISSIONS.ASSESSMENT_QUESTIONS_VIEW,
    PERMISSIONS.ASSESSMENT_QUESTIONS_UPDATE,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_CREATE,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_VIEW,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_UPDATE,
    PERMISSIONS.ATTEMPTS_VIEW,
    PERMISSIONS.PROCTORING_VIEW,
    PERMISSIONS.PROCTORING_REVIEW,
    PERMISSIONS.EVALUATIONS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_EXPORT,
    PERMISSIONS.CERTIFICATES_VIEW,
    PERMISSIONS.CERTIFICATES_EXPORT,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  [ORGANIZATION_ROLES.EXAMINER]: [
    PERMISSIONS.ORG_PROFILE_VIEW,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.PROGRAMS_VIEW,
    PERMISSIONS.SUBJECTS_VIEW,
    PERMISSIONS.QUESTION_BANKS_CREATE,
    PERMISSIONS.QUESTION_BANKS_VIEW,
    PERMISSIONS.QUESTION_BANKS_UPDATE,
    PERMISSIONS.QUESTIONS_CREATE,
    PERMISSIONS.QUESTIONS_VIEW,
    PERMISSIONS.QUESTIONS_UPDATE,
    PERMISSIONS.QUESTION_CATEGORIES_CREATE,
    PERMISSIONS.QUESTION_CATEGORIES_VIEW,
    PERMISSIONS.QUESTION_CATEGORIES_UPDATE,
    PERMISSIONS.QUESTION_TAGS_CREATE,
    PERMISSIONS.QUESTION_TAGS_VIEW,
    PERMISSIONS.QUESTION_TAGS_UPDATE,
    PERMISSIONS.ASSESSMENTS_CREATE,
    PERMISSIONS.ASSESSMENTS_VIEW,
    PERMISSIONS.ASSESSMENTS_UPDATE,
    PERMISSIONS.ASSESSMENTS_PUBLISH,
    PERMISSIONS.ASSESSMENTS_ARCHIVE,
    PERMISSIONS.ASSESSMENT_SECTIONS_CREATE,
    PERMISSIONS.ASSESSMENT_SECTIONS_VIEW,
    PERMISSIONS.ASSESSMENT_SECTIONS_UPDATE,
    PERMISSIONS.ASSESSMENT_QUESTIONS_ADD,
    PERMISSIONS.ASSESSMENT_QUESTIONS_VIEW,
    PERMISSIONS.ASSESSMENT_QUESTIONS_UPDATE,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_CREATE,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_VIEW,
    PERMISSIONS.ATTEMPTS_VIEW,
    PERMISSIONS.EVALUATIONS_CREATE,
    PERMISSIONS.EVALUATIONS_VIEW,
    PERMISSIONS.EVALUATIONS_UPDATE,
    PERMISSIONS.EVALUATIONS_SUBMIT,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_GENERATE,
    PERMISSIONS.RESULTS_PUBLISH,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
  ],

  [ORGANIZATION_ROLES.PROCTOR]: [
    PERMISSIONS.ORG_PROFILE_VIEW,
    PERMISSIONS.ASSESSMENTS_VIEW,
    PERMISSIONS.ASSESSMENT_ASSIGNMENTS_VIEW,
    PERMISSIONS.ATTEMPTS_VIEW,
    PERMISSIONS.PROCTORING_VIEW,
    PERMISSIONS.PROCTORING_MONITOR,
    PERMISSIONS.PROCTORING_REVIEW,
    PERMISSIONS.PROCTORING_FLAG,
    PERMISSIONS.PROCTORING_RESOLVE,
  ],

  [ORGANIZATION_ROLES.CANDIDATE]: [
    PERMISSIONS.ATTEMPTS_CREATE,
    PERMISSIONS.ATTEMPTS_VIEW_OWN,
    PERMISSIONS.ATTEMPTS_UPDATE_OWN,
    PERMISSIONS.ATTEMPTS_SUBMIT_OWN,
    PERMISSIONS.EVALUATIONS_VIEW_OWN,
    PERMISSIONS.RESULTS_VIEW_OWN,
    PERMISSIONS.CERTIFICATES_VIEW_OWN,
    PERMISSIONS.REPORTS_VIEW_OWN,
  ],
};

/**
 * Seeds all granular permissions and system roles with their assigned permissions
 */
export const seedRBAC = async () => {
  logger.info("[Seeder] Starting RBAC Seeder...");

  // 1. Seed Permissions
  const permissionDocs = {};
  for (const key of PERMISSION_LIST) {
    const [resource, ...actionParts] = key.split(".");
    const action = actionParts.join(".");
    const isPlatform =
      key.startsWith("platform.") ||
      key.startsWith("platform_users.") ||
      key.startsWith("subscriptions.") ||
      key.startsWith("billing.") ||
      key.startsWith("system_configuration.") ||
      key.startsWith("roles.") ||
      key.startsWith("permissions.") ||
      (key.startsWith("organizations.") && !key.startsWith("organizations.profile."));

    const scope = isPlatform ? ROLE_SCOPES.PLATFORM : ROLE_SCOPES.ORGANIZATION;

    const doc = await Permission.findOneAndUpdate(
      { key },
      {
        key,
        resource,
        action,
        scope,
        description: `Allows ${action} action on ${resource} resource`,
      },
      { upsert: true, new: true }
    );
    permissionDocs[key] = doc._id;
  }
  logger.info(`[Seeder] Seeded ${Object.keys(permissionDocs).length} permissions.`);

  // 2. Seed System Roles with Linked Permissions
  const systemRoles = [
    {
      name: PLATFORM_ROLES.PLATFORM_OWNER,
      scope: ROLE_SCOPES.PLATFORM,
      description: "Root platform owner with absolute authority over SecureAssess",
      permissions: ROLE_PERMISSION_MATRIX[PLATFORM_ROLES.PLATFORM_OWNER].map(
        (k) => permissionDocs[k]
      ),
    },
    {
      name: PLATFORM_ROLES.PLATFORM_ADMIN,
      scope: ROLE_SCOPES.PLATFORM,
      description: "Platform administrator with operational authority",
      permissions: ROLE_PERMISSION_MATRIX[PLATFORM_ROLES.PLATFORM_ADMIN].map(
        (k) => permissionDocs[k]
      ),
    },
    {
      name: ORGANIZATION_ROLES.ORGANIZATION_OWNER,
      scope: ROLE_SCOPES.ORGANIZATION,
      description: "Primary administrator and owner of an organization tenant",
      permissions: ROLE_PERMISSION_MATRIX[ORGANIZATION_ROLES.ORGANIZATION_OWNER].map(
        (k) => permissionDocs[k]
      ),
    },
    {
      name: ORGANIZATION_ROLES.ORGANIZATION_ADMIN,
      scope: ROLE_SCOPES.ORGANIZATION,
      description: "Organization administrator for day-to-day tenant operations",
      permissions: ROLE_PERMISSION_MATRIX[ORGANIZATION_ROLES.ORGANIZATION_ADMIN].map(
        (k) => permissionDocs[k]
      ),
    },
    {
      name: ORGANIZATION_ROLES.EXAMINER,
      scope: ROLE_SCOPES.ORGANIZATION,
      description: "Examiner responsible for question banks, assessments, and grading",
      permissions: ROLE_PERMISSION_MATRIX[ORGANIZATION_ROLES.EXAMINER].map(
        (k) => permissionDocs[k]
      ),
    },
    {
      name: ORGANIZATION_ROLES.PROCTOR,
      scope: ROLE_SCOPES.ORGANIZATION,
      description: "Live exam proctor and integrity supervisor",
      permissions: ROLE_PERMISSION_MATRIX[ORGANIZATION_ROLES.PROCTOR].map(
        (k) => permissionDocs[k]
      ),
    },
    {
      name: ORGANIZATION_ROLES.CANDIDATE,
      scope: ROLE_SCOPES.ORGANIZATION,
      description: "Candidate examinee with strictly isolated self-access",
      permissions: ROLE_PERMISSION_MATRIX[ORGANIZATION_ROLES.CANDIDATE].map(
        (k) => permissionDocs[k]
      ),
    },
  ];

  for (const roleDef of systemRoles) {
    await Role.findOneAndUpdate(
      { name: roleDef.name, scope: roleDef.scope, organizationId: null },
      {
        name: roleDef.name,
        scope: roleDef.scope,
        description: roleDef.description,
        isSystemRole: true,
        permissions: roleDef.permissions,
        organizationId: null,
      },
      { upsert: true, new: true }
    );
  }

  logger.info(`[Seeder] Seeded ${systemRoles.length} system roles with permission relationships.`);
};
