export const QUESTION_TYPES = Object.freeze({
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  TRUE_FALSE: 'TRUE_FALSE',
  SHORT_ANSWER: 'SHORT_ANSWER',
  ESSAY: 'ESSAY',
  CODING: 'CODING',
  VIDEO_RESPONSE: 'VIDEO_RESPONSE',
  AUDIO_VIDEO_RESPONSE: 'AUDIO_VIDEO_RESPONSE',
});

export const QUESTION_TYPE_LIST = Object.values(QUESTION_TYPES);
