export const ASSESSMENT_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  APPROVED: 'APPROVED',
  PUBLISHED: 'PUBLISHED',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
});

export const ATTEMPT_STATUSES = Object.freeze({
  INVITED: 'INVITED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  TERMINATED: 'TERMINATED',
});

export const RESULT_STATUSES = Object.freeze({
  PENDING_REVIEW: 'PENDING_REVIEW',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  FLAGGED: 'FLAGGED',
});
